version: '3'
volumes:
  db_data:

# TODO: dockerize doesn't always get all code changes
# NB: this doesn't actually run out of uwsgi and nginx
#
services:

  web:
    build: . 
    # build + image = tags this image build
    image: "silverwebapp:latest"

    command: dockerize -wait tcp://db:3306 -timeout 30s /code/docker-scripts/docker-entrypoint

    environment: &WEB_ENVIRONMENT
      # - SILVER_TEST_SHELL=no

      - AUTHORIZE_API_LOGIN=asdf
      - AUTHORIZE_TRANSACTION_KEY=asdf
      - AUTHORIZE_KEY=asdf

      - ANTIKYTHERA_DB_NAME=silver
      - ANTIKYTHERA_DB_HOST=db
      - ANTIKYTHERA_DB_USER=silver
      - ANTIKYTHERA_DB_PASS=silver
      - ANTIKYTHERA_DB_PORT=3306

      - SILVER_MIGRATE=yes
      - SILVER_LOAD_DEV_DATA=yes
      - SILVER_RUN_TESTS=no

      - REDIS_HOST_STRING=redis://redis:6379/0
      - DJANGO_BROKER_URL=redis://redis:6379/1

    ports:
      - "8080:8080"

    volumes: &WEB_VOLUMES
      - ./app/dev_dot_com:/app
      - ./silver:/code/silver
      - ./infra/antikythera:/code/antikythera
      - ./silver-authorize:/code/silver_authorizenet

    depends_on:
      - db
      - celery

  celery:
    # This is almost exactly the same as `web`
    image: silverwebapp:latest
    # -Q default
    command: "celery -A silverintegration worker -l info -B"
    working_dir: "/app/silverintegration"
    environment: *WEB_ENVIRONMENT
    volumes: *WEB_VOLUMES
    depends_on:
      - db
      - redis

  db:
    image: "nimmis/alpine-mariadb"
    restart: always
    volumes:
      - db_data:/var/lib/mysql 
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: silver
      MARIADB_DATABASE: silver
      MARIADB_USER: silver
      MARIADB_PASSWORD: silver

  redis:
    image: "redis:3.2-alpine"
    ports:
     - "6379:6379"
