version: '3'
volumes:
  db_data:

# TODO: dockerize doesn't always get all code changes
# NB: this doesn't actually run out of uwsgi and nginx
#
services:
  web:
    build: .
    # build + image = tags this image build
    image: "silverwebapp:latest"

    command: dockerize -wait tcp://db:3306 -timeout 30s /app/docker-entrypoint

    environment: &WEB_ENVIRONMENT
      - DJANGO_SETTINGS_MODULE=silverintegration.settings

      - AUTHORIZE_API_LOGIN=asdf
      - AUTHORIZE_TRANSACTION_KEY=asdf
      - AUTHORIZE_KEY=asdf

      - SILVER_DB_ENGINE=django.db.backends.mysql
      - SILVER_DB_NAME=silver
      - SILVER_DB_HOST=db
      - SILVER_MIGRATE=yes
      - SILVER_LOAD_DEV_DATA=yes
      - SILVER_RUN_TESTS=no

      - REDIS_HOST_STRING=redis://redis:6379/0
      - DJANGO_BROKER_URL=pyamqp://

    ports:
      - "8080:8080"

    volumes: &WEB_VOLUMES
      - ./app/dev_dot_com:/app
      - ./silver:/code/silver
      - ./silver-authorize:/code/silver_authorizenet

    depends_on:
      - db

  celery:
    # This is almost exactly the same as `web`
    image: silverwebapp:latest
    command: "celery worker -A silverintegration -l info -B"
    working_dir: "/app/silverintegration"
    environment: *WEB_ENVIRONMENT
    volumes: *WEB_VOLUMES
    depends_on:
      - db
      - redis
      - web

  db:
    image: "yobasystems/alpine-mariadb"
    restart: always
    volumes:
      - db_data:/var/lib/mysql 
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: silver
      MYSQL_DATABASE: silver
      MYSQL_USER: silver
      MYSQL_PASSWORD: silver

  redis:
    image: "redis:3.2-alpine"
    ports:
     - "6379:6379"
