# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-20 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import silver.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('silver', '0050_auto_20190206_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteredfeature',
            name='included_units_calculation',
            field=models.CharField(blank=True, help_text='A formula to calculate included units.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='meteredfeature',
            name='linked_feature',
            field=silver.utils.models.UnsavedForeignKey(blank=True, help_text='A related feature.', null=True, on_delete=django.db.models.deletion.CASCADE, to='silver.MeteredFeature'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fail_code',
            field=models.CharField(blank=True, choices=[('invalid_payment_method', 'invalid_payment_method'), ('invalid_card', 'invalid_card'), ('default', 'default'), ('limit_exceeded', 'limit_exceeded'), ('transaction_hard_declined_by_bank', 'transaction_hard_declined_by_bank'), ('transaction_declined_by_bank', 'transaction_declined_by_bank'), ('transaction_hard_declined', 'transaction_hard_declined'), ('transaction_declined', 'transaction_declined'), ('expired_payment_method', 'expired_payment_method'), ('expired_card', 'expired_card'), ('insufficient_funds', 'insufficient_funds')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=django_fsm.FSMField(choices=[('failed', 'Failed'), ('initial', 'Initial'), ('settled', 'Settled'), ('canceled', 'Canceled'), ('pending', 'Pending'), ('refunded', 'Refunded')], default='initial', max_length=8),
        ),
    ]
