# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-14 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silver', '0050_auto_20190206_2158'),
        ('silver', '0051_auto_20181230_2007'),
    ]

    operations = [
    ]
