# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-21 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silver', '0051_auto_20190220_2129'),
        ('silver', '0052_merge_20190214_2042'),
    ]

    operations = [
    ]
