# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-23 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm
import silver.models.documents.pdf


class Migration(migrations.Migration):

    dependencies = [
        ('silver', '0054_auto_20190221_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteredfeature',
            name='prebill_included_units',
            field=models.NullBooleanField(help_text='If this is set to True, then the total of included units will be pre-billed at the beginning of the cycle.'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_processor',
            field=models.CharField(choices=[('manual', 'manual')], max_length=256),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='pdf_file',
            field=models.FileField(blank=True, editable=False, null=True, upload_to=silver.models.documents.pdf.get_upload_path),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fail_code',
            field=models.CharField(blank=True, choices=[('expired_card', 'expired_card'), ('transaction_declined_by_bank', 'transaction_declined_by_bank'), ('default', 'default'), ('limit_exceeded', 'limit_exceeded'), ('expired_payment_method', 'expired_payment_method'), ('invalid_payment_method', 'invalid_payment_method'), ('invalid_card', 'invalid_card'), ('transaction_hard_declined_by_bank', 'transaction_hard_declined_by_bank'), ('transaction_declined', 'transaction_declined'), ('transaction_hard_declined', 'transaction_hard_declined'), ('insufficient_funds', 'insufficient_funds')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=django_fsm.FSMField(choices=[('initial', 'Initial'), ('canceled', 'Canceled'), ('failed', 'Failed'), ('pending', 'Pending'), ('refunded', 'Refunded'), ('settled', 'Settled')], default='initial', max_length=8),
        ),
    ]
