#!/bin/sh
set -e

if [ "$SILVER_MIGRATE" == "yes" ] ; then
/usr/local/bin/python3 /app/silverintegration/manage.py migrate --noinput
fi

if [ "$SILVER_LOAD_DEV_DATA" == "yes" ] ; then
    /usr/local/bin/python3 /app/silverintegration/manage.py loaddata -i fixtures/initial_dev_data.json
fi


if [ "$SILVER_RUN_TESTS" == "yes" ] ; then
    make test
else
    exec /usr/local/bin/python3 /app/silverintegration/manage.py runserver 0.0.0.0:8080
fi

