#!/bin/sh
set -e

if [ "$SILVER_TEST_SHELL" == "yes" ] ; then
    cd /code/silver && \
        pip install -r requirements/test.txt && \
        pip install watchdog
    exit;
fi

if [ "$SILVER_MIGRATE" == "yes" ] ; then
    antikythera-manage migrate --noinput
    # Dev purposes only, obviously.
    echo "from django.contrib.auth.models import User; User.objects.create_superuser('root', 'admin@example.com', 'adminadmin')" | antikythera-manage shell
fi

if [ "$SILVER_LOAD_DEV_DATA" == "yes" ] ; then
    # NB: run once
    if [ ! -f fixtures.installed ] ; then
        antikythera-manage loaddata -i docker-fixtures.json
    fi
    antikythera-manage createinitialrevisions
    touch fixtures.installed
fi


if [ "$SILVER_RUN_TESTS" == "yes" ] ; then
    make test
else
    if [ "$SILVER_LOAD_DEV_DATA" == "yes" ] ; then
        echo "TEST ADMIN USER: root / adminadmin"
    fi
    exec antikythera-manage runserver 0.0.0.0:8080
fi

