# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-30 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('silver', '0049_auto_20181102_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_processor',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fail_code',
            field=models.CharField(blank=True, choices=[('transaction_declined', 'transaction_declined'), ('limit_exceeded', 'limit_exceeded'), ('default', 'default'), ('expired_payment_method', 'expired_payment_method'), ('insufficient_funds', 'insufficient_funds'), ('invalid_payment_method', 'invalid_payment_method'), ('expired_card', 'expired_card'), ('invalid_card', 'invalid_card'), ('transaction_declined_by_bank', 'transaction_declined_by_bank'), ('transaction_hard_declined', 'transaction_hard_declined'), ('transaction_hard_declined_by_bank', 'transaction_hard_declined_by_bank')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=django_fsm.FSMField(choices=[('pending', 'Pending'), ('refunded', 'Refunded'), ('canceled', 'Canceled'), ('settled', 'Settled'), ('failed', 'Failed'), ('initial', 'Initial')], default='initial', max_length=8),
        ),
    ]
