# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-06 21:58
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django_fsm
import silver.models.documents.pdf


class Migration(migrations.Migration):

    dependencies = [
        ('silver', '0049_auto_20181102_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='overpayment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
