# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-21 02:08
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django_fsm
import silver.models.documents.pdf


class Migration(migrations.Migration):

    dependencies = [
        ('silver', '0053_merge_20190221_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_processor',
            field=models.CharField(choices=[('AuthorizeNetTriggered', 'AuthorizeNetTriggered'), ('authorizenet_triggered', 'authorizenet_triggered'), ('manual', 'manual')], max_length=256),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='pdf_file',
            field=models.FileField(blank=True, editable=False, null=True, storage=django.core.files.storage.FileSystemStorage(location='/opt/sites/dev.billing.dynamicic.com/silverintegration/documents/'), upload_to=silver.models.documents.pdf.get_upload_path),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fail_code',
            field=models.CharField(blank=True, choices=[('expired_payment_method', 'expired_payment_method'), ('limit_exceeded', 'limit_exceeded'), ('transaction_hard_declined_by_bank', 'transaction_hard_declined_by_bank'), ('invalid_payment_method', 'invalid_payment_method'), ('transaction_hard_declined', 'transaction_hard_declined'), ('insufficient_funds', 'insufficient_funds'), ('default', 'default'), ('transaction_declined', 'transaction_declined'), ('expired_card', 'expired_card'), ('transaction_declined_by_bank', 'transaction_declined_by_bank'), ('invalid_card', 'invalid_card')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=django_fsm.FSMField(choices=[('initial', 'Initial'), ('refunded', 'Refunded'), ('failed', 'Failed'), ('pending', 'Pending'), ('settled', 'Settled'), ('canceled', 'Canceled')], default='initial', max_length=8),
        ),
    ]
