# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-25 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('silver', '0055_auto_20190223_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fail_code',
            field=models.CharField(blank=True, choices=[('default', 'default'), ('insufficient_funds', 'insufficient_funds'), ('expired_card', 'expired_card'), ('expired_payment_method', 'expired_payment_method'), ('invalid_card', 'invalid_card'), ('transaction_hard_declined', 'transaction_hard_declined'), ('limit_exceeded', 'limit_exceeded'), ('transaction_hard_declined_by_bank', 'transaction_hard_declined_by_bank'), ('transaction_declined', 'transaction_declined'), ('invalid_payment_method', 'invalid_payment_method'), ('transaction_declined_by_bank', 'transaction_declined_by_bank')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=django_fsm.FSMField(choices=[('refunded', 'Refunded'), ('pending', 'Pending'), ('initial', 'Initial'), ('settled', 'Settled'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='initial', max_length=8),
        ),
    ]
