# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-13 21:32
from __future__ import unicode_literals

from decimal import Decimal
import django.core.files.storage
from django.db import migrations, models
import django_fsm
import silver.models.documents.pdf


class Migration(migrations.Migration):

    dependencies = [
        ('silver', '0056_auto_20190225_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cycle_end_override',
            field=models.DateField(blank=True, default=None, help_text='The date when the subscription cycle ends.', null=True),
        ),
        migrations.AlterField(
            model_name='billingdocumentbase',
            name='transaction_xe_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('1'), help_text='Currency exchange rate from document currency to transaction_currency.', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_processor',
            field=models.CharField(choices=[('manual', 'manual'), ('authorizenet_triggered', 'authorizenet_triggered'), ('AuthorizeNetTriggered', 'AuthorizeNetTriggered')], max_length=256),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='pdf_file',
            field=models.FileField(blank=True, editable=False, null=True, storage=django.core.files.storage.FileSystemStorage(location='/code/antikythera/antikythera/documents/'), upload_to=silver.models.documents.pdf.get_upload_path),
        ),
        migrations.AlterField(
            model_name='plan',
            name='interval',
            field=models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('monthish', 'Month-ish'), ('year', 'Year')], default='month', help_text='The frequency with which a subscription should be billed.', max_length=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fail_code',
            field=models.CharField(blank=True, choices=[('default', 'default'), ('insufficient_funds', 'insufficient_funds'), ('expired_payment_method', 'expired_payment_method'), ('expired_card', 'expired_card'), ('invalid_payment_method', 'invalid_payment_method'), ('invalid_card', 'invalid_card'), ('limit_exceeded', 'limit_exceeded'), ('transaction_declined', 'transaction_declined'), ('transaction_declined_by_bank', 'transaction_declined_by_bank'), ('transaction_hard_declined', 'transaction_hard_declined'), ('transaction_hard_declined_by_bank', 'transaction_hard_declined_by_bank')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=django_fsm.FSMField(choices=[('initial', 'Initial'), ('pending', 'Pending'), ('settled', 'Settled'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], default='initial', max_length=8),
        ),
    ]
