# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-15 01:22
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import silver.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('silver', '0057_auto_20190313_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='linked_subscription',
            field=silver.utils.models.UnsavedForeignKey(blank=True, help_text='A related subscription, allowing for calculating linked feature totals.', null=True, on_delete=django.db.models.deletion.CASCADE, to='silver.Subscription'),
        ),
    ]
