# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 20:53
from __future__ import unicode_literals

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import silver.models.documents.pdf
import uuid

def create_uuid(apps, schema_editor):
    Customer = apps.get_model('silver', 'Customer')
    for customer in Customer.objects.all():
        customer.uuid = uuid.uuid4()
        customer.save()

class Migration(migrations.Migration):

    dependencies = [
        ('silver', '0058_subscription_linked_subscription'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='customer',
        #     name='uuid',
        #     field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, null=True),
        # ),
        migrations.AddField(
            model_name='customer',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='customer',
            name='uuid',
            field=models.UUIDField(unique=True, default=uuid.uuid4, editable=False, null=True)
        ),
        migrations.AlterField(
            model_name='pdf',
            name='pdf_file',
            field=models.FileField(blank=True, editable=False, null=True, storage=django.core.files.storage.FileSystemStorage(location='/code/src/infra/antikythera/antikythera/documents/'), upload_to=silver.models.documents.pdf.get_upload_path),
        ),
        migrations.AlterField(
            model_name='plan',
            name='interval_count',
            field=models.PositiveIntegerField(help_text='The number of intervals between each subscription billing', validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
