# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('silver', '0059_auto_20190328_2053'),
    ]

    operations = [
        migrations.RenameField(
            'customer',
            'uuid',
            'account_id',
        ),
    ]
